Add identifier creation
naccdata/flywheel-gear-extensions pull request #76
Opened 2024-06-18 21:53 UTC by bjkeller

Adds the identifier-provisioning gear that processes the participant enrollment/transfer form.
The gear reads form data from a CSV and creates batches for new enrollments and transfers.
Creates an enrollment JSON file on the new subject in the enrollment project, adds identifiers to the subject metadata, and adds transfers to the project.

Sets gear image tag to 0.1.0

2024-06-21 19:17 UTC, hewanadun requested changes
Looks good overall. There are couple places that return values need to be interchanged True<->False, please check the comments.
Also, we decided to retrieve the module info from the input file name suffix, so 'module' will not be a required column in the file.

2024-06-25 15:22 UTC, bjkeller commented
I forgot to make a new branch for the GUID updates, so these are mixed in with these fixes.

2024-06-26 14:52 UTC, hewanadun submitted a review, later dismissed
Few minor changes, please check the comments.

2024-06-26 14:52 UTC, hewanadun commented on common/src/python/identifiers/identifiers_repository.py
> +          identifier: the Identifier object to add
update docstring args

2024-06-26 14:52 UTC, hewanadun commented on common/src/python/identifiers/identifiers_repository.py
>            ptid: the participant ID assigned by the center
add guid to docstring

2024-06-26 14:52 UTC, hewanadun commented on common/src/python/identifiers/identifiers_lambda_repository.py
> +          NoMatchingIdentifier: if no Identifier record was found
Raises IdentifierRepositoryError

2024-06-26 14:52 UTC, hewanadun commented on gear/identifier_provisioning/src/python/identifier_provisioning_app/main.py
> +                             line=line_num))
Add custom error message here, default message is not correct for this scenario

2024-06-26 14:52 UTC, hewanadun commented on gear/identifier_provisioning/src/python/identifier_provisioning_app/main.py
> +        self.__naccid_identifier = self.__repo.get(naccid=self.__naccid)
handle exception?

2024-06-26 14:52 UTC, hewanadun commented on gear/identifier_provisioning/src/python/identifier_provisioning_app/main.py
> +        guid_identifier = self.__repo.get(guid=row['guid'])
handle exception?

2024-06-26 14:52 UTC, hewanadun commented on gear/identifier_provisioning/src/python/identifier_provisioning_app/main.py
> +        ptid_identifier = self.__repo.get(adcid=previous_adcid,
handle exception?

2024-06-26 14:52 UTC, hewanadun commented on gear/identifier_provisioning/src/python/identifier_provisioning_app/main.py
> +                               f"Guid {source} "
It seems {source} is not always GUID here

2024-06-26 14:52 UTC, hewanadun commented on gear/identifier_provisioning/src/python/identifier_provisioning_app/main.py
> +          line_num: the line number
add source to docstring

2024-06-28 16:04 UTC, merged